# Generated by TsaoDFT. Review cube volume, camera, colors, and output before execution.
# source: {{CUBE_FILE}}
# camera_id: {{CAMERA_ID}}
color Display Background white
display projection Orthographic
display resize {{WIDTH}} {{HEIGHT}}
axes location Off
mol new "{{CUBE_FILE}}" type cube waitfor all
mol delrep 0 top
mol representation CPK 1.0 0.3 24 24
mol color Name
mol material Opaque
mol addrep top
mol representation Isosurface {{ISOVALUE}} 0 0 0 1 1
mol color ColorID {{POSITIVE_COLOR_ID}}
mol material Opaque
mol addrep top
mol representation Isosurface -{{ISOVALUE}} 0 0 0 1 1
mol color ColorID {{NEGATIVE_COLOR_ID}}
mol material Opaque
mol addrep top
{{CAMERA_COMMANDS}}
render TachyonInternal "{{OUTPUT_TGA}}"
quit
