# Generated by TsaoDFT. Density cube is volume 0; ESP cube is volume 1.
# density source: {{DENSITY_CUBE}}
# ESP source: {{ESP_CUBE}}
# camera_id: {{CAMERA_ID}}
color Display Background white
display projection Orthographic
display resize {{WIDTH}} {{HEIGHT}}
axes location Off
mol new "{{DENSITY_CUBE}}" type cube waitfor all
mol addfile "{{ESP_CUBE}}" type cube waitfor all
mol delrep 0 top
mol representation CPK 1.0 0.3 24 24
mol color Name
mol material Opaque
mol addrep top
mol representation Isosurface {{DENSITY_ISOVALUE}} 0 0 0 1 1
mol color Volume 1
mol material Transparent
mol addrep top
set repid [expr {[molinfo top get numreps] - 1}]
mol scaleminmax top $repid {{ESP_MIN}} {{ESP_MAX}}
color scale method {{COLOR_MAP}}
{{CAMERA_COMMANDS}}
render TachyonInternal "{{OUTPUT_TGA}}"
quit
