import React, { useMemo, useState } from 'react';
import { Download, Maximize2, RotateCcw, Search } from 'lucide-react';
import { RESIN_NETWORK, type ResinNetworkNode } from '@/data/resinData';
const point=(node:ResinNetworkNode,index:number,total:number)=>{const resin=node.group==='resin';const count=Math.max(1,total);const angle=(index/count)*Math.PI*2;const radius=resin?185:100;return{x:300+Math.cos(angle)*radius,y:220+Math.sin(angle)*radius};};
const DependencyMapD3:React.FC=()=>{const[query,setQuery]=useState('');const[selected,setSelected]=useState<ResinNetworkNode|null>(null);const[labels,setLabels]=useState(true);const[fullscreen,setFullscreen]=useState(false);
 const positions=useMemo(()=>new Map(RESIN_NETWORK.nodes.map((n,i)=>[n.id,point(n,i,RESIN_NETWORK.nodes.length)])),[]);const filtered=RESIN_NETWORK.nodes.filter(n=>!query||n.id.toLowerCase().includes(query.toLowerCase()));
 const exportJson=()=>{const blob=new Blob([JSON.stringify(RESIN_NETWORK,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='resindb-resin-network.json';a.click();URL.revokeObjectURL(url);};
 return <section data-testid="dependency-map" className={`${fullscreen?'fixed inset-0 z-[240]':'h-full'} flex flex-col rounded-2xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-950`}><div className="mb-3 flex flex-wrap items-center gap-2"><label className="relative flex-1"><Search className="absolute left-2 top-2.5" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索单体或树脂" className="w-full rounded-lg border py-2 pl-8 pr-2 text-sm"/></label><button type="button" onClick={()=>{setQuery('');setSelected(null);}} title="复位"><RotateCcw size={16}/></button><button type="button" onClick={()=>setLabels(!labels)} className="rounded-lg border px-2 py-1 text-xs">标签</button><button type="button" onClick={()=>setFullscreen(!fullscreen)} title="全屏"><Maximize2 size={16}/></button><button type="button" onClick={exportJson} title="导出 JSON"><Download size={16}/></button></div>
 <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[1fr_220px]"><svg role="img" aria-label="树脂原料与聚合物关系图" data-testid="dependency-map-svg" viewBox="0 0 600 440" className="h-full min-h-[420px] w-full rounded-xl bg-slate-50 dark:bg-slate-900">{RESIN_NETWORK.links.map((l,i)=>{const a=positions.get(String(l.source)),b=positions.get(String(l.target));return a&&b?<line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="currentColor" opacity=".2" strokeWidth={l.value??1}/>:null;})}{filtered.map(n=>{const p=positions.get(n.id)!;return <g key={n.id} onClick={()=>setSelected(n)} className="cursor-pointer"><circle cx={p.x} cy={p.y} r={Math.max(8,n.radius??14)} fill={n.group==='resin'?'var(--color-primary-500,#6366f1)':'#94a3b8'} stroke="white" strokeWidth="2"/><title>{n.id}</title>{labels&&<text x={p.x} y={p.y+(n.radius??14)+13} textAnchor="middle" fontSize="10" fill="currentColor">{n.id}</text>}</g>;})}</svg><aside className="rounded-xl border p-3 text-sm dark:border-slate-700"><h3 className="font-bold">网络分析</h3><p className="mt-2 text-xs text-slate-500">节点 {RESIN_NETWORK.nodes.length}；关系 {RESIN_NETWORK.links.length}。点击节点查看原料、分子式与用途说明。</p>{selected&&<dl className="mt-4 space-y-2 text-xs"><dt className="font-bold">{selected.id}</dt><dd>{selected.group}</dd>{selected.formula&&<dd>分子式：{selected.formula}</dd>}{selected.cas&&<dd>CAS：{selected.cas}</dd>}<dd>{selected.desc??'未提供说明'}</dd></dl>}</aside></div></section>;
};
export default DependencyMapD3;
